sudo: false
language: c
cache:
  directories:
  - $HOME/.stack

before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
- export PATH=/opt/ghc/$GHCVER/bin:$PATH

matrix:
  include:
  - env: STACK_YAML=stack-8.4.yaml
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-8.4.4
        - build-essential
  - env: STACK_YAML=stack-8.6.yaml
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-8.6.4
        - build-essential

script:
 - stack --no-terminal --system-ghc build elf-edit
 - stack --no-terminal --system-ghc test elf-edit
