name: CI
on:
  push:

jobs:
  build:
    strategy:
      matrix:
        cabal: ["3.14.2.0"]
        ghc: ["9.8.4", "9.10.1", "9.12.2"]
        os: ["ubuntu-24.04"]
      fail-fast: false
    name: GHC v${{ matrix.ghc }}
    uses: GaloisInc/.github/.github/workflows/haskell-ci.yml@v1
    with:
      cabal: ${{ matrix.cabal }}
      check: false
      # See Note [Parallelism] in `haskell-ci.yml` for why `--ghc-options='-j'`
      # and `--semaphore`.
      configure-flags: --enable-tests --ghc-options='-Wall -Werror -j' --semaphore
      ghc: ${{ matrix.ghc }}
      os: ${{ matrix.os }}
      pre-hook: |
        mv cabal.project.freeze.ghc-${{ matrix.ghc }} cabal.project.freeze
      # Test binaries are not currently included in the sdist
      sdist: false
